import {THREE,createWorld,textPanel,mesh} from './world.js';
import {createGame,SEQUENCES,STORE_KEY} from './state.js';
import {GardenAudio} from './audio.js';
const $=id=>document.getElementById(id),canvas=$('world');
let w;try{w=createWorld(canvas)}catch(e){$('error').hidden=false;throw e}
const {renderer,scene,camera,rig,stations}=w;
let saved=null,prefs={};try{saved=JSON.parse(localStorage.getItem(STORE_KEY));prefs=JSON.parse(localStorage.getItem(STORE_KEY+'-settings'))||{}}catch{}
const game=createGame(saved),audio=new GardenAudio();audio.volume=typeof prefs.volume==='number'?THREE.MathUtils.clamp(prefs.volume,0,1):.45;
let reduced=typeof prefs.reduced==='boolean'?prefs.reduced:matchMedia('(prefers-reduced-motion: reduce)').matches;
let started=false,place='overview',moving=false,wateringUntil=0,wateringIndex=0,petUntil=0,lastTime=0,melodyRun=0,playingMelody=false,activeBell=-1,bellPulseUntil=0,endingTimer=0;
let orbitYaw=.57,orbitPitch=.44,orbitDistance=24,orbitTarget=new THREE.Vector3(-2,.35,0);
let currentActions=[],currentMessage='',labels=[],grabbed=null,xrBoard=null,xrButtons=[],xrControllers=[],xrFrameReady=false,xrSwitching=false,lastSnap=0;
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),tempMatrix=new THREE.Matrix4(),tmpV=new THREE.Vector3();const interactables=[];
const ids=['garden','library','bells'];const symbols=['Luna','Hoja','Taza'];const colors=['Rosa','Dorada','Violeta'];
const stories=w.books.map((book,i)=>{const g=new THREE.Group();book.group.add(g);g.position.set(0,.58,.24);if(i===0){const moon=mesh(g,new THREE.TorusGeometry(.13,.035,8,20,Math.PI*1.5),'#f8db9c',[0,0,0]);moon.rotation.z=.65;mesh(g,'ball','#fff1c7',[.17,.09,.02],[.025,.025,.025],{emissive:'#ffe4a0',emissiveIntensity:1});}if(i===1){mesh(g,'cyl','#b38d7d',[0,-.05,0],[.09,.12,.09]);mesh(g,'cyl','#8ca781',[0,.07,0],[.014,.2,.014]);for(const side of [-1,1]){const leaf=mesh(g,'ball','#afd0a2',[side*.06,.09,0],[.075,.035,.035]);leaf.rotation.z=side*.45;}}if(i===2){mesh(g,'cyl','#edd3ab',[0,0,0],[.105,.14,.105]);mesh(g,'cyl','#906d64',[0,.073,0],[.082,.006,.082]);mesh(g,new THREE.TorusGeometry(.057,.015,6,16),'#edd3ab',[.11,0,0]);for(let j=0;j<3;j++)mesh(g,'ball','#eee2d9',[.02*Math.sin(j),.15+j*.07,0],[.018,.03,.018],{transparent:true,opacity:.5});}return g;});
let dusk=game.state.finished?1:0;const daySky=new THREE.Color('#a88b9b'),nightSky=new THREE.Color('#685576');

function save(){try{localStorage.setItem(STORE_KEY,JSON.stringify(game.state))}catch{}}
function savePrefs(){try{localStorage.setItem(STORE_KEY+'-settings',JSON.stringify({volume:audio.volume,reduced,audio:audio.enabled}))}catch{}}
function action(id,label,run,opts={}){return {id,label,run,...opts}}
function say(text){currentMessage=text;$('message').textContent=text;updateXRBoard()}
function bindObject(object,actionId,title,station){object.userData.actionId=actionId;object.userData.title=title;object.userData.station=station;interactables.push(object)}
w.flowers.forEach((f,i)=>bindObject(f.group,'water'+i,'Regar: '+colors[i], 'garden'));
w.tokens.forEach((t,i)=>bindObject(t.group,'token'+i,'Coger '+symbols[i].toLowerCase(),'library'));
w.books.forEach((b,i)=>bindObject(b.group,'book'+i,'Libro de '+symbols[i].toLowerCase(),'library'));
w.bells.forEach((b,i)=>bindObject(b.group,'bell'+i,['Do','Mi','Sol'][i],'bells'));
bindObject(w.capy,'pet','Acariciar a Mimo','capy');bindObject(w.lanternGroup,'finish','Encender el farol','lantern');w.stars.forEach((s,i)=>bindObject(s,'collect'+i,'Recoger estrella',ids[i]));
function count(){return game.state.stars.filter(Boolean).length}
function updateProgress(){stories.forEach((g,i)=>g.visible=game.state.books[i]);const n=count();$('stars').textContent=game.state.stars.map(s=>s?'✦':'✧').join(' ');$('star-count').textContent=`${n} / 3`;$('star-count').parentElement.setAttribute('aria-label',`${n} de 3 estrellas despiertas`);ids.forEach((id,i)=>{document.querySelector(`[data-place="${id}"] i`).textContent=game.state.stars[i]?'✓':'';const s=w.stars[i];s.material.color.set(game.state.stars[i]?'#ffe4a3':solved(i)?'#f8d899':'#a59ab8');s.material.emissiveIntensity=game.state.stars[i]?1.1:solved(i)?.6:0;s.position.copy(stations[id].pos).add(new THREE.Vector3(0,2.8,.1));if(game.state.stars[i])s.position.set((i-1)*.52,1.9,-.6);});w.festoon.forEach(b=>b.material.emissiveIntensity=game.state.finished?2:.05);w.lanternLight.intensity=game.state.finished?7:0;const flame=w.lanternGroup.children.find(m=>m.isMesh&&m.material.emissive?.getHexString()==='f0b64f');if(flame)flame.material.emissiveIntensity=game.state.finished?3:.1;w.flowers.forEach((f,i)=>{const amount=game.state.water[i]/3;f.head.scale.setScalar(.48+amount*.52);f.head.rotation.z=amount===1?0:-.2;});w.tokens.forEach((t,i)=>{if(game.state.books[i]){t.group.visible=false;w.books[i].label.userData.setText(['☾ ✧','❧ ✧','☕ ✧'][i]);}else{t.group.visible=true;w.books[i].label.userData.setText(['☾','❧','☕'][i]);}});}
function solved(i){return i===0?game.state.water.every(v=>v===3):i===1?game.state.books.every(Boolean):game.state.bellRound===3}
function renderActions(actions){const focused=document.activeElement?.dataset?.action;currentActions=actions;$('actions').replaceChildren(...actions.map(a=>{const b=document.createElement('button');b.textContent=a.label;b.dataset.action=a.id;b.disabled=!!a.disabled;b.classList.toggle('selected',!!a.selected);b.classList.toggle('completed',!!a.completed);b.onclick=()=>perform(a.id);return b}));if(focused)$('actions').querySelector(`[data-action="${focused}"]`)?.focus({preventScroll:true});updateXRBoard()}
function perform(id){if(!started||moving||$('settings').open||!$('ending').hidden)return;const a=currentActions.find(a=>a.id===id);if(a&&!a.disabled){a.run();save();updateProgress();}}
function collect(i){if(game.collect(i)){audio.sparkle();updateProgress();refreshActions();say(count()===3?'¡Las tres estrellas están despiertas! Nos espera el farol bajo el árbol.':`Una estrella más. Ya llevamos ${count()} de tres. Gracias por cuidarla.`);}}
function refreshActions(){let actions=[];if(place==='overview'){actions=[action('go-garden','❀ Visitar el invernadero',()=>visit('garden')),action('go-capy','♡ Conocer a Mimo',()=>visit('capy'))];if(count()===3)actions.unshift(action('go-lantern',game.state.finished?'✧ Volver al farol':'✧ Encender el farol',()=>visit('lantern')))}
 if(place==='garden'){actions=w.flowers.map((_,i)=>action('water'+i,`${game.state.water[i]===3?'✓':'♧'} ${colors[i]} · ${game.state.water[i]}/3`,()=>water(i),{completed:game.state.water[i]===3,disabled:game.state.water[i]===3||performance.now()<wateringUntil}));}
 if(place==='library'){actions=[];for(let i=0;i<3;i++){if(!game.state.books[i])actions.push(action('token'+i,`${game.selected===i?'✧ ':'Coger '}${symbols[i].toLowerCase()}`,()=>selectToken(i),{selected:game.selected===i}));}if(game.selected!==null)for(let i=0;i<3;i++)if(!game.state.books[i])actions.push(action('book'+i,'Libro: '+symbols[i].toLowerCase(),()=>placeToken(i)));}
 if(place==='bells'){actions=[action('listen',playingMelody?'Escuchando…':'♫ Escuchar la melodía',playMelody,{disabled:playingMelody})];w.bells.forEach((_,i)=>actions.push(action('bell'+i,`${i+1} · ${['Do','Mi','Sol'][i]}`,()=>hitBell(i),{disabled:playingMelody})));}
 if(place==='capy'){actions=[action('pet','♡ Acariciar a Mimo',pet),action('sit','Quedarme a su lado',()=>say('No hace falta hacer nada. Podemos escuchar el agua y respirar un ratito. Mimo es especialista en eso.'))];}
 if(place==='lantern'){actions=[action('finish',game.state.finished?'✧ Volver a ver la celebración':'✧ Colocar las tres estrellas',finish,{disabled:count()<3})];}
 const idx=ids.indexOf(place);if(idx>=0&&solved(idx)){if(!game.state.stars[idx])actions=[action('collect'+idx,'✦ Recoger la estrella',()=>collect(idx))];else actions.push(action('go-overview','Volver al jardín',()=>visit('overview')));}
 renderActions(actions);}
function greeting(){if(place==='overview')return game.state.finished?'El jardín ya tiene su luz. Puedes quedarte, visitar a Mimo y hacer sonar las campanillas.':count()===3?'¡Tenemos las tres estrellas! Acércate al farol bajo el árbol para devolverle la luz al jardín.':'Soy Pylara. Me alegra que estés aquí. Visita los tres rincones y despierta sus estrellas. Mimo también quiere conocerte.';
 if(place==='garden')return game.state.stars[0]?'Las flores ya cantan. Su estrella está a salvo en el farol.':solved(0)?'¡Ya cantan las tres! Su estrella está lista para acompañarnos.':'Estas flores tienen mucha sed y un poquito de sueño. Dales tres sorbitos de agua a cada una.';
 if(place==='library')return game.state.stars[1]?'Los libros han recuperado sus historias. Gracias por reunirlas.':solved(1)?'Cada historia ha vuelto a su lugar. ¡Mira la estrella!':'El viento mezcló las cubiertas. Coge una pieza y colócala en el libro con el mismo dibujo.';
 if(place==='bells')return game.state.stars[2]?'Puedes seguir haciendo música. El jardín te escucha.':solved(2)?'¡Qué bien suena! La última nota ha despertado una estrella.':`Escucha y repite las luces de las campanillas. Melodía ${game.state.bellRound+1} de 3. No pasa nada si te equivocas.`;
 if(place==='capy')return 'Este es Mimo, nuestro carpincho. Guarda mandarinas y ratitos de calma. Acércate y dale una caricia.';
 return game.state.finished?'Las cosas pequeñas también iluminan mundos. Este rincón siempre será tuyo.':count()===3?'Ya están todas. Coloca las tres estrellas en el farol y mira lo que sucede.':`El farol espera sus tres estrellas. Todavía nos faltan ${3-count()}.`;}
function setPlaceUI(){document.querySelectorAll('[data-place]').forEach(b=>{b.classList.toggle('active',b.dataset.place===place);b.setAttribute('aria-current',b.dataset.place===place?'location':'false')});$('chapter').textContent=place==='overview'?'EL JARDÍN':place==='capy'?'UN AMIGO':place==='lantern'?'LA LUZ':`RINCÓN ${ids.indexOf(place)+1} / 3`;$('place-title').textContent=place==='overview'?'El jardín de las pequeñas alegrías':stations[place].title;$('hint').hidden=place==='capy'||game.state.finished;refreshActions();say(greeting());}
function updateCamera(){if(renderer.xr.isPresenting)return;camera.position.set(orbitTarget.x+Math.sin(orbitYaw)*Math.cos(orbitPitch)*orbitDistance,orbitTarget.y+Math.sin(orbitPitch)*orbitDistance,orbitTarget.z+Math.cos(orbitYaw)*Math.cos(orbitPitch)*orbitDistance);camera.lookAt(orbitTarget);}
function poseForPlace(){const mobile=innerWidth<=760;if(place==='overview'){orbitTarget.set(!started?-2.3:0,.1,0);orbitYaw=.57;orbitPitch=.49;orbitDistance=mobile?31:24;if(!started&&mobile)orbitTarget.set(0,-4.3,0);}else{orbitTarget.copy(stations[place].pos).add(new THREE.Vector3(mobile?0:-.43,mobile?.64:1.03,0));orbitYaw=place==='capy'?.18:.05;orbitPitch=place==='capy'?.29:.18;orbitDistance=mobile?6:4.7;}updateCamera();}
async function visit(id,instant=false){if(id!=='overview'&&!stations[id])throw Error('Rincón desconocido');if(moving)return;if(!started)start(false);moving=true;stopMelody();returnGrab();game.cancelSelection();$('hover-label').hidden=true;if(!instant&&!reduced&&!renderer.xr.isPresenting){$('transition').style.opacity='1';await new Promise(r=>setTimeout(r,150));}place=id;setPlaceUI();if(renderer.xr.isPresenting)teleportXR();else poseForPlace();$('transition').style.opacity='0';if(!instant&&!reduced&&!renderer.xr.isPresenting)await new Promise(r=>setTimeout(r,170));moving=false;}
function start(withAudio=true){if(started)return;started=true;document.body.classList.add('playing');$('welcome').hidden=true;$('companion').hidden=false;$('places').hidden=false;if(withAudio&&prefs.audio!==false)enableAudio();setPlaceUI();poseForPlace();}
function water(i){if(performance.now()<wateringUntil||game.state.water[i]===3)return;const value=game.water(i);wateringIndex=i;wateringUntil=performance.now()+850;audio.water();audio.tone([392,523.25,659.25][i],.5,.4,'sine',.13);say(value===3?[ 'La rosa ha bostezado… ¡y ahora canta!', 'La dorada te regala una nota de sol.', '¡Achís! La violeta acaba de despertar.' ][i]:['Un sorbito. Ya empieza a desperezarse.','Otro poquito. Mira cómo abre sus pétalos.'][value-1]);refreshActions();setTimeout(()=>{if(place==='garden'){refreshActions();if(solved(0))say('¡Las tres flores están cantando! Recoge la estrella que han despertado.')}},870);}
function selectToken(i){if(game.select(i)){audio.tone(440,.2);say(`Tienes la pieza de ${symbols[i].toLowerCase()}. Ahora elige su libro.`);refreshActions();}}
function placeToken(i){const result=game.place(i);if(result==='placed'){audio.sparkle();returnGrab();updateProgress();refreshActions();say(solved(1)?'Luna, hoja y taza: cada historia ha vuelto a su lugar. ¡Una estrella!':['La luna vuelve a iluminar sus páginas.','El bosque vuelve a crecer entre las letras.','El té vuelve a estar calentito.'][i]);}else say(result==='empty'?'Primero coge una pieza de la mesa.':'Casi. Mira el dibujo de la pieza y busca el mismo en la cubierta.');}
function stopMelody(){melodyRun++;playingMelody=false;activeBell=-1;game.resetMelody();}
async function playMelody(){if(playingMelody)return;game.resetMelody();const run=++melodyRun;playingMelody=true;refreshActions();say('Escucha y mira las luces. Después te toca a ti.');const sequence=SEQUENCES[Math.min(game.state.bellRound,2)];await new Promise(r=>setTimeout(r,450));for(const i of sequence){if(run!==melodyRun)return;activeBell=i;bellPulseUntil=performance.now()+500;audio.bell(i);await new Promise(r=>setTimeout(r,850));}if(run!==melodyRun)return;activeBell=-1;playingMelody=false;refreshActions();say(`Ahora tú: ${sequence.length} notas. Puedes escucharla de nuevo cuando quieras.`);}
function hitBell(i){if(playingMelody)return;audio.bell(i);activeBell=i;bellPulseUntil=performance.now()+500;if(game.state.bellRound===3)return;const result=game.note(i);if(result==='retry')say('Esa nota quería ir por otro camino. Volvemos al principio de esta melodía; puedes escucharla otra vez.');else if(result==='round'){say(`¡Eso es! Vamos con la melodía ${game.state.bellRound+1} de 3. Pulsa «Escuchar».`);audio.sparkle();}else if(result==='solved'){say('¡Qué melodía tan bonita! Has despertado la estrella de las campanillas.');audio.sparkle();}else say(`Bien, llevamos ${game.bellInput.length} de ${SEQUENCES[game.state.bellRound].length} notas.`);refreshActions();}
function pet(){game.pet();petUntil=performance.now()+3000;audio.pet();say(['Mimo cierra los ojos. Creo que acabas de convertirte en su persona favorita.','Una caricia, una mandarina y ninguna prisa. Mimo no necesita mucho más.','Mimo te responde con un ronroneo pequeñito. Sí, puedes quedarte.'][ (game.state.pets-1)%3 ]);}
function finish(){if(!game.finish())return;say('Las cosas pequeñas también iluminan mundos. Gracias por devolvernos la luz.');audio.sparkle();petUntil=performance.now()+6000;setTimeout(()=>audio.sparkle(),900);updateProgress();refreshActions();clearTimeout(endingTimer);endingTimer=setTimeout(()=>{if(!renderer.xr.isPresenting){$('ending').hidden=false;document.querySelector('.topbar').inert=true;$('companion').inert=true;$('places').inert=true;$('world-labels').inert=true;canvas.tabIndex=-1;$('stay').focus();}},1800);}
function hint(){const hints={overview:'Los letreros te llevan a cada rincón. Riega las flores, reúne las cubiertas y repite la melodía. Cada rincón guarda una estrella.',garden:'Pulsa cada flor tres veces, dejando que termine cada sorbito. También puedes usar los botones Rosa, Dorada y Violeta.',library:'La luna va con la luna; la hoja con la hoja; la taza con la taza. Primero la pieza, después el libro.',bells:`La siguiente melodía es: ${SEQUENCES[Math.min(game.state.bellRound,2)].map(i=>['Do','Mi','Sol'][i]).join(' · ')}.`,lantern:'Recoge la estrella de cada rincón después de resolverlo. Cuando tengas tres, pulsa el farol.'};say(hints[place]||greeting());}
$('hint').onclick=hint;$('start').onclick=()=>start();$('home').onclick=e=>{e.preventDefault();if(started)visit('overview')};document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>visit(b.dataset.place));$('stay').onclick=()=>{$('ending').hidden=true;document.querySelector('.topbar').inert=false;$('companion').inert=false;$('places').inert=false;$('world-labels').inert=false;canvas.tabIndex=0;visit('overview')};
$('settings-open').onclick=()=>{$('reset-confirm').hidden=true;$('settings').showModal()};
async function enableAudio(){const ok=await audio.start();if(!ok){$('settings-vr-info').textContent='No hemos podido activar el sonido en este navegador. Puedes seguir jugando con las luces.'}updateSound();}
function updateSound(){$('sound').classList.toggle('sound-on',audio.enabled);$('sound').setAttribute('aria-label',audio.enabled?'Silenciar sonido':'Activar sonido');$('sound').title=audio.enabled?'Silenciar sonido':'Activar sonido';$('audio-enabled').checked=audio.enabled;savePrefs()}
$('sound').onclick=()=>{if(audio.enabled){audio.setEnabled(false);updateSound()}else enableAudio()};$('audio-enabled').onchange=()=>{if($('audio-enabled').checked)enableAudio();else{audio.setEnabled(false);updateSound()}};$('volume').value=audio.volume*100;$('volume').oninput=()=>{audio.setVolume(Number($('volume').value)/100);savePrefs()};$('motion').checked=reduced;$('motion').onchange=()=>{reduced=$('motion').checked;savePrefs()};$('reset').onclick=()=>{$('reset-confirm').hidden=false};$('reset-no').onclick=()=>{$('reset-confirm').hidden=true};$('reset-yes').onclick=()=>{stopMelody();clearTimeout(endingTimer);game.reset();save();updateProgress();$('settings').close();$('ending').hidden=true;if(started)visit('overview',true);else{setPlaceUI();poseForPlace();}$('start').innerHTML='Entrar al jardín <span>✧</span>'};
for(const [id,s] of Object.entries(stations)){const b=document.createElement('button');b.className='place-label';b.innerHTML=`<span>${s.icon}</span>${s.short}`;b.onclick=()=>visit(id);$('world-labels').append(b);labels.push({id,button:b,pos:s.pos.clone().add(new THREE.Vector3(0,id==='capy'?1.9:3.2,0))});}
// Pointer, touch and keyboard all use the same actions as the accessible controls.
let down=null;canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(down){const dx=e.clientX-down.lastX,dy=e.clientY-down.lastY;down.moved ||= Math.hypot(e.clientX-down.x,e.clientY-down.y)>6;if(down.moved){orbitYaw-=dx*.005;orbitPitch=THREE.MathUtils.clamp(orbitPitch+dy*.004,.06,1.1);updateCamera()}down.lastX=e.clientX;down.lastY=e.clientY;}else{const obj=hitAt(e.clientX,e.clientY);$('hover-label').hidden=!obj||!started||place==='overview';if(obj){$('hover-label').textContent=obj.userData.title;$('hover-label').style.left=Math.min(e.clientX+14,innerWidth-170)+'px';$('hover-label').style.top=e.clientY+18+'px'}canvas.style.cursor=obj?'pointer':'grab'}});
canvas.addEventListener('pointerup',e=>{if(down&&!down.moved){const o=hitAt(e.clientX,e.clientY);if(o){if(place==='overview')visit(o.userData.station);else perform(o.userData.actionId)}}down=null});canvas.addEventListener('pointercancel',()=>down=null);canvas.addEventListener('pointerleave',()=>{$('hover-label').hidden=true});canvas.addEventListener('wheel',e=>{e.preventDefault();orbitDistance=THREE.MathUtils.clamp(orbitDistance+e.deltaY*.009,place==='overview'?17:3.2,place==='overview'?38:8);updateCamera()},{passive:false});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')orbitYaw+=.1;if(e.key==='ArrowRight')orbitYaw-=.1;if(e.key==='ArrowUp')orbitPitch=Math.min(1.1,orbitPitch+.07);if(e.key==='ArrowDown')orbitPitch=Math.max(.06,orbitPitch-.07);updateCamera()}});
function relevantObjects(){return interactables.filter(o=>o.visible&&(place==='overview'||o.userData.station===place))}
function getRoot(o){while(o&&!o.userData.actionId)o=o.parent;return o}
function hitAt(x,y){pointer.set(x/innerWidth*2-1,-y/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);return getRoot(raycaster.intersectObjects(relevantObjects(),true)[0]?.object)}
// Small water droplets are recycled, rather than allocated while playing.
const drops=[];for(let i=0;i<16;i++){const d=mesh(w.dynamics,'ball','#c5e2dd',[0,0,0],[.025,.05,.025],{transparent:true,opacity:.8});d.visible=false;drops.push(d)}
const canHome=w.can.position.clone();
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();poseForPlace();}window.addEventListener('resize',resize);
// WebXR uses the same world and state; HTML is replaced by actual 3D signs.
async function enterVR(){if(xrSwitching)return;if(renderer.xr.isPresenting){await renderer.xr.getSession().end();return}const info=$('vr-info');const explain=t=>{info.hidden=false;info.textContent=t;$('settings-vr-info').textContent=t;};if(!window.isSecureContext){explain('Abre el enlace publicado con https en el navegador de tus Meta Quest para entrar en realidad virtual.');return}if(!navigator.xr){explain('Abre este mismo juego en el navegador de tus Meta Quest y pulsa aquí. En este dispositivo puedes jugar en la pantalla.');return}xrSwitching=true;let session;try{if(!await navigator.xr.isSessionSupported('immersive-vr')){explain('Este navegador no tiene unas gafas disponibles. Abre el juego en el navegador de tus Meta Quest.');return}session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor']});$('settings').close();start();renderer.xr.setReferenceSpaceType('local-floor');await renderer.xr.setSession(session);}catch(e){if(session)await session.end().catch(()=>{});explain('No se ha iniciado la realidad virtual. Comprueba el permiso de las gafas y vuelve a pulsar el botón.');}finally{xrSwitching=false}}
$('vr').onclick=enterVR;$('vr-settings').onclick=enterVR;
function disposePanel(g){g.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.map?.dispose();o.material.dispose()}});g.removeFromParent()}
function updateXRBoard(){if(!renderer.xr.isPresenting||!xrBoard)return;for(const c of [...xrBoard.children])disposePanel(c);xrButtons=[];const title=textPanel(`PYLARA · ${count()} / 3 estrellas`,1.65,.25,{size:34});title.position.y=.65;xrBoard.add(title);const msg=textPanel(currentMessage,1.65,.69,{size:31});msg.position.y=.16;xrBoard.add(msg);const entries=[...currentActions,action('hint','Una pista',hint),action('audio-xr',audio.enabled?'Silenciar':'Activar sonido',()=>{if(audio.enabled){audio.setEnabled(false);updateSound()}else enableAudio();updateXRBoard()})];for(const [i,a] of entries.entries()){const b=textPanel(a.label,.8,.23,{bg:a.disabled?'#5d5268':a.selected?'#827063':'#51435e',color:a.completed?'#b7d6ad':'#fff1d8',size:51});b.position.set((i%2?1:-1)*.425,-.36-Math.floor(i/2)*.28,0);b.userData.xrAction=()=>{if(!a.disabled){a.run();save();updateProgress()}};xrBoard.add(b);xrButtons.push(b)}}
const xrNav=new THREE.Group();scene.add(xrNav);xrNav.visible=false;const navKeys=['overview','garden','library','bells','capy'];const navButtons=[];navKeys.forEach((id,i)=>{const b=textPanel(id==='overview'?'Jardín / Farol':stations[id].short,.67,.19,{size:69});b.position.set((i-2)*.72,0,0);b.userData.xrAction=()=>visit(id==='overview'?'lantern':id);xrNav.add(b);navButtons.push(b)});const exitButton=textPanel('Salir de VR',.62,.19,{size:75});exitButton.position.set(0,-.25,0);exitButton.userData.xrAction=()=>renderer.xr.getSession()?.end();xrNav.add(exitButton);navButtons.push(exitButton);
function teleportXR(){const id=place==='overview'?'lantern':place;const p=stations[id].pos;rig.rotation.set(0,0,0);rig.position.set(p.x,0,p.z+2.7);xrFrameReady=false;if(!xrBoard){xrBoard=new THREE.Group();scene.add(xrBoard)}xrBoard.position.set(p.x-1.6,1.32,p.z+1.15);xrBoard.rotation.y=.42;xrBoard.visible=true;xrNav.position.set(p.x,.55,p.z+1);xrNav.visible=true;updateXRBoard();}
renderer.xr.addEventListener('sessionstart',()=>{renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;stopMelody();$('ending').hidden=true;camera.position.set(0,0,0);camera.rotation.set(0,0,0);place=place==='overview'?'lantern':place;setPlaceUI();teleportXR();});
renderer.xr.addEventListener('sessionend',()=>{returnGrab();xrNav.visible=false;if(xrBoard)xrBoard.visible=false;rig.position.set(0,0,0);rig.rotation.set(0,0,0);renderer.shadowMap.autoUpdate=true;poseForPlace();});
function rayController(controller){tempMatrix.identity().extractRotation(controller.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(controller.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(tempMatrix);return raycaster.intersectObjects([...relevantObjects(),...xrButtons,...navButtons],true)[0]}
function selectXR(controller){const hit=rayController(controller);if(!hit)return;if(hit.object.userData.xrAction)hit.object.userData.xrAction();else{const o=getRoot(hit.object);if(o)perform(o.userData.actionId)}}
function returnGrab(){if(!grabbed)return;const {index}=grabbed;w.dynamics.attach(w.tokens[index].group);w.tokens[index].group.position.copy(w.tokens[index].home);w.tokens[index].group.rotation.set(0,0,0);grabbed=null;}
for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);rig.add(controller);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-1)]),new THREE.LineBasicMaterial({color:'#f5d89b',transparent:true,opacity:.55}));line.scale.z=3;controller.add(line);const dot=mesh(controller,'ball','#ffe6ae',[0,0,-3],[.014,.014,.014],{emissive:'#ffe6ae',emissiveIntensity:1});controller.addEventListener('selectstart',()=>selectXR(controller));controller.addEventListener('connected',e=>controller.userData.source=e.data);controller.addEventListener('disconnected',()=>{returnGrab();controller.userData.source=null});controller.addEventListener('squeezestart',()=>{if(place!=='library'||grabbed)return;const hit=rayController(controller),root=getRoot(hit?.object);const index=w.tokens.findIndex(t=>t.group===root);if(index>=0&&!game.state.books[index]){selectToken(index);controller.attach(w.tokens[index].group);w.tokens[index].group.position.set(0,-.03,-.18);grabbed={index,controller}}});controller.addEventListener('squeezeend',()=>{if(!grabbed||grabbed.controller!==controller)return;const token=w.tokens[grabbed.index].group;const wp=token.getWorldPosition(new THREE.Vector3());let nearest=-1,dist=.65;w.books.forEach((b,j)=>{const d=b.group.getWorldPosition(new THREE.Vector3()).distanceTo(wp);if(d<dist){nearest=j;dist=d}});if(nearest>=0)placeToken(nearest);returnGrab();save();});xrControllers.push({controller,line,dot});}
function updateXR(){if(!renderer.xr.isPresenting)return;if(!xrFrameReady){const head=renderer.xr.getCamera().getWorldPosition(tmpV);if(head.y>.2){const base=stations[place==='overview'?'lantern':place].pos;rig.position.y=1.6-head.y;rig.position.x+=base.x-head.x;rig.position.z+=base.z+2.7-head.z;xrFrameReady=true}}for(const {controller,line,dot} of xrControllers){const hit=rayController(controller);line.scale.z=hit?Math.min(hit.distance,6):3;dot.position.z=-line.scale.z;const axes=controller.userData.source?.gamepad?.axes;if(axes&&Math.abs(axes[2]??axes[0])>.75&&performance.now()-lastSnap>350){rig.rotation.y-=Math.sign(axes[2]??axes[0])*Math.PI/6;lastSnap=performance.now()}}}
function frame(time){const t=time*.001,dt=Math.min(.05,t-lastTime||.016);lastTime=t;dusk=THREE.MathUtils.damp(dusk,game.state.finished?1:0,1.2,dt);scene.background.copy(daySky).lerp(nightSky,dusk);scene.fog.color.copy(scene.background);w.sun.intensity=3.3-dusk*1.7;stories.forEach((g,i)=>{g.rotation.y=reduced?0:Math.sin(t*.7+i)*.18;});if(!reduced){w.fairy.position.y=2.05+Math.sin(t*2)*.12;w.fairy.rotation.y=Math.sin(t*.7)*.3;w.motes.rotation.y=t*.012;w.capyHead.rotation.x=performance.now()<petUntil?Math.sin(t*5)*.04:Math.sin(t)*.012;w.capy.scale.y=1+Math.sin(t*1.5)*.008;w.water.scale.y=.055+Math.sin(t)*.003;}else{w.capyHead.rotation.x=0;w.capy.scale.y=1;}w.stars.forEach((s,i)=>{if(!reduced)s.rotation.y=t*.6+i});w.capyHead.children.forEach(o=>{if(o.userData.eye)o.scale.y=performance.now()<petUntil?.008:.033});w.capyHearts.visible=performance.now()<petUntil;if(w.capyHearts.visible)w.capyHearts.children.forEach((h,i)=>{h.position.y=1.7+i*.12+(1-(petUntil-performance.now())/3000)*.7;h.quaternion.copy(camera.quaternion)});
 const pouring=performance.now()<wateringUntil;if(pouring){const f=w.flowers[wateringIndex].group.position;w.can.position.set(f.x-.3,1.85,f.z+.1);w.can.rotation.z=-.55;drops.forEach((d,i)=>{d.visible=true;const a=((time*.002+i/16)%1);d.position.set(f.x+Math.sin(i*5)*.07,1.7-a*.72,f.z+Math.cos(i*2)*.07)})}else{w.can.position.copy(canHome);w.can.rotation.z=0;drops.forEach(d=>d.visible=false)}
 w.tokens.forEach((tk,i)=>{if(grabbed?.index===i)return;tk.group.position.y=tk.home.y+(game.selected===i?.18:0);});w.bells.forEach((b,i)=>{b.group.rotation.z=!reduced&&i===activeBell&&performance.now()<bellPulseUntil?Math.sin(t*24)*.12:0;b.bell.material.emissive.set(i===activeBell&&performance.now()<bellPulseUntil?'#ffd889':'#000000');b.bell.material.emissiveIntensity=.7;});
 updateXR();if(!renderer.xr.isPresenting)for(const l of labels){const visible=place==='overview'&&started||!started&&l.id==='capy';l.button.hidden=!visible;if(visible){const v=l.pos.clone().project(camera);l.button.style.left=(v.x*.5+.5)*innerWidth+'px';l.button.style.top=(-v.y*.5+.5)*innerHeight+'px';l.button.style.visibility=v.z>1||v.z<0?'hidden':'visible';}}
 audio.tick(t,game.state.finished);renderer.render(scene,camera);
}
updateProgress();poseForPlace();renderer.setAnimationLoop(frame);document.body.dataset.ready='true';$('start').disabled=false;$('start').innerHTML=(count()||game.state.water.some(Boolean)||game.state.books.some(Boolean)||game.state.bellRound?'Volver a mi jardín':'Entrar al jardín')+' <span>✧</span>';
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').hidden=false;$('error-message').textContent='Los gráficos se han detenido. Tu avance está guardado: recarga para volver al jardín.'});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMelody();if(started)refreshActions();audio.ctx?.suspend()}else if(audio.enabled)audio.ctx?.resume()});
// Structured access mirrors the visible navigation, without exposing hidden puzzle answers.
if(document.modelContext?.registerTool){const controller=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}};register({name:'read_garden_progress',description:'Read collected stars, completed activities and the current place.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({place,stars:count(),flowers:game.state.water,books:game.state.books,bellRound:game.state.bellRound,finished:game.state.finished})});register({name:'visit_garden_corner',description:'Start the game if needed and travel to a named corner, using the same navigation as the player.',inputSchema:{type:'object',properties:{place:{type:'string',enum:['overview',...Object.keys(stations)]}},required:['place'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!['overview',...Object.keys(stations)].includes(input.place))throw Error('Rincón desconocido');if(moving)throw Error('El viaje anterior todavía no ha terminado');await visit(input.place);return {place,description:currentMessage}}});window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
